project:
  type: website

website:
  title: "Cameron Patrick"
  site-url: https://cameronpatrick.com/
  favicon: Cam_headshot_small.jpg
  twitter-card:
    creator: "@camjpatrick"
  open-graph: true
  navbar:
    right:
      - blog.qmd
      - icon: twitter
        href: https://twitter.com/camjpatrick
      - icon: github
        href: https://github.com/cmrnp
format:
  html:
    theme: simplex
    css: styles.css
    fontsize: 1.2em
    linestretch: 1.7
    mainfont: Helvetica, Arial, sans
    monofont: Cascadia Mono, Menlo, Courier New
    backgroundcolor: white
    knitr:
      opts_chunk:
        dev: "ragg_png"

editor: source

