{
  "hash": "daf27c883cdb7a2b08d3954f0579289a",
  "result": {
    "markdown": "---\ntitle: \"You are what you ATE: Choosing an effect size measure for binary outcomes\"\nauthor: \"Cameron Patrick\"\ndate: \"2023-07-13\"\ndraft: true\ncategories: [r, statistics]\ncsl: apa.csl\nbibliography: \n  - odds-ratios.yaml\nformat:\n  html:\n    toc: true\nabstract: |\n  | Wherein I try to make sense of ongoing debates in the statistical community about how to analyse and report clinical trials targeting binary outcomes, and then write some R code to practice what I hesitantly preach.\n---\n\n\n\n\n\n## The great odds ratio debate (with memes)\n\nA lot of noise has been made about why an odds ratio may not be a desirable summary for a treatment effect on a binary variable[^orrefs]. There is that pesky problem that normal humans are unable to correctly interpret an odds ratio [@altman1998oddsratiosshould]. In recent years, people[^stat] have become more aware of the mathematical fact of noncollapsibility [@greenland1999confoundingcollapsibilitycausal; @daniel2021makingapplesoranges; @morris2022planningmethodcovariate]: the marginal[^econstat] odds ratio (population-level odds ratio) is not any kind of average of conditional odds ratios (individual-level odds ratios)[^longitudinal]. The [ICH E9(R1) estimand framework for clinical trials](https://database.ich.org/sites/default/files/E9-R1_Step4_Guideline_2019_1203.pdf) requires a \"population-level summary\". In the language of causal inference, that's describing an Average Treatment Effect (ATE), and the odds ratio isn't one[^coxreg].\n\n[^orrefs]: For a recent example, see [this talk by Jonathan Bartlett](https://thestatsgeek.com/2023/06/23/is-the-ich-e9-estimand-addendum-compatible-with-model-based-estimands/).\n\n[^stat]: Statisticians.\n\n[^econstat]: Statisticians use the word \"marginal\" to refer to a population-level average, or an integral. Economists, on the other hand, use the word \"marginal\" to refer to a change in a quantity, or a derivative. This could never cause any confusion.\n\n[^longitudinal]: This issue is also sometimes raised in longitudinal studies, where it is said that generalised linear mixed models (GLMMs) target conditional odds ratios while generalised estimating equations (GEEs) target marginal odds ratios. As far as I understand it, this is only half true: odds ratios from GEEs target what you'd get from a GLMM after marginalising over random effects, but are still conditional on other covariates in the model (fixed effects in a GLMM).\n\n[^coxreg]: Neither is the hazard ratio, despite the ubiquity of Cox regression for survival analysis.\n\nRisk differences (the difference in probability attributable to a particular treatment) and relative risks (the ratio of probabilities due to a particular treatment) avoid these problems of odds ratios. However, statisticians are usually taught to analyse binary outcomes using logistic regression, the direct output[^logdirect] of which is odds ratios. Someone on Stats Twitter rediscovers all of this every few months and starts a heated argument where nobody goes away happy.\n\n[^logdirect]: Technically, logistic regression directly estimates a conditional difference of log-odds. The difference on the log scale is usually exponentiated and reported as an odds ratio.\n\n![Surprisingly, many statisticians prefer collapsibility.](building-collapse.jpg){fig-alt=\"Picture of a collapsing building with the caption \\\"I'll take the non-collapsible one\\\"\"}\n\nPersonally, I'm a fan of risk differences for communicating potential risks to an individual, ideally presented alongside the baseline level of risk. There's some evidence that patients and clinicians find these measures easier to interpret than relative measures [@zipkin2014evidencebasedriskcommunication], especially when presented in the form of a natural frequency, like \"6 in 1000 people\" rather than \"0.6%\".\n\nStatistical analyses are often adjusted for covariates, either to reduce confounding (in observational studies) or improve power (in randomised trials). There are some technical challenges when doing this with risk differences and relative risks. Adjusting for covariates requires specifying some kind of model. If we're using a generalised linear model[^gam], the natural mathematical form of covariate adjustment will depend on whether you are modelling log-odds (logistic regression model, where model parameters correspond to an odds ratio), probability (linear probability model, where model parameters correspond to a risk difference) or log-probability (quasi-Poisson or log-link binomial model, where model parameters correspond to a relative risk). When modelling risk differences or relative risks directly, it's possible to end up with impossible predicted probabilities: \"probabilities\" which are less than zero or greater than one. Using logistic regression avoids this problem, because any real number on the log-odds scale translates to a probability between zero and one. Any odds ratio can be applied to any level of baseline risk without making mathematicians sad[^mathsad].\n\n[^gam]: Or even an additive model --- exactly the same point applies to Generalised Additive Models.\n\n[^mathsad]: At this point you may find yourself inclined to avoid logistic regression purely to spite the mathematicians. I don't blame you.\n\nThere are also compelling --- but not universally accepted --- arguments that despite the difficulty in interpreting odds ratios, they are more likely to be transportable between different levels of baseline risk than risk differences or relative risks [@doi2022controversydebatequestionable; @senn2011uneasereasonsmistrusting]. This is an empirical matter, not a mathematical one, and the evidence is not clear-cut. If we accept this, though, it is another reason to prefer logistic regression for statistical modelling. Effect size measures being \"transportable\" is another way of saying that the effects are closer to being additive on the scale that effect measure lives on (probability, log-probability, or log-odds). In the context of regression models, using a scale where the effect size is more transportable reduces the need for interaction terms, which can only be estimated well in large samples.\n\nThus we have a dilemma: people understand risk differences and (to a lesser extent) relative risks, but they can be problematic to estimate with covariate adjustment; nobody understands odds ratios[^interpor], but logistic regression is probably a better model, operating closer to a scale on which the underlying effects are additive. One possible way out is to model the data using logistic regression, and then use that model to produce other quantities of interest. This approach is described in @permutt2020covariateschangeestimand, which has some of the best writing I've encountered in a statistics paper --- being written in the form of a dialogue between a randomiser (the \"causal inference\" perspective) and a parameteriser (the \"statistical modelling\" perspective) walking through the Garden of Eden, planning to conduct and analyse a clinical trial.\n\n[^interpor]: If you can intuitively interpret odds ratios, that's great for you, although I'm not sure I believe you.\n\n@permutt2020covariateschangeestimand also considered what information different audiences might want from the results of a clinical trial: regulator, patient, and scientist. There's a fourth audience which I think is worth considering, only very briefly mentioned by Permutt: the meta-analyst, trying to aggregate information from multiple trials.\n\nPermutt argues in favour of the ATE being the main quantity of regulatory interest:\n\n> The average treatment effect should be of regulatory interest, however. The primary analysis of outcome should be of a variable that is reasonably linear in utility to the patient. Then, if and only if the average effect is positive, the ensemble of patients can be said to be better off under the test condition than under the control. This is perhaps the weakest imaginable statistical condition for approval of a drug product, but it is surely a necessary condition.\n\nPermutt notes that studies designed to be able to detect average treatment effects are unlikely to be adequate for patient-specific decision making or providing a more detailed scientific understanding.\n\nThe most clearly expressed counter-argument to this comes from [a blog post by Frank Harrell arguing against single-number summaries for treatment effects on binary outcomes](https://www.fharrell.com/post/rdist/):\n\n> Marginal adjusted estimates may be robust, but may not accurately estimate RD for either any patient in the RCT or for the clinical population to which RCT results are to be applied, because in effect they assume that the RCT sample is a random sample from the clinical population, something not required and never realized for RCTs.\n\nThis refers to the distinction between the population average treatment effect (PATE) and the sample average treatment effect (SATE). RCT participants are not random samples from any population, not even from the eligible pool of participants for a particular study. But the regulator's decision that Permutt described earlier is motivated by generalising to a broader population, implicitly relying on properties of the PATE. It's not clear to me whether there are likely to be any real-world scenarios where both (1) the practical conclusions drawn from the SATE and PATE would be different; and (2) the conditional odds ratio derived from the RCT sample is in agreement with the PATE but the risk difference SATE is not.\n\nI am a coward and not (yet?) willing to take a strong position in this fight, but am always sympathetic to the idea that a single number is rarely sufficient to describe scientific evidence (see also: p-values). At some point I might write another blog about Harrell's idea of plotting the distribution of estimated patient-level treatment effects, which is intriguing, although I struggle to see the practical purpose of it. Harrell's other writing on this topic is also worth reading:\n\n- [Incorrect Covariate Adjustment May Be More Correct than Adjusted Marginal Estimates](https://www.fharrell.com/post/robcov/) makes a similar point to @white2021covariateadjustmentrandomised with a detailed simulated example;\n- [Assessing Heterogeneity of Treatment Effect, Estimating Patient-Specific Efficacy, and Studying Variation in Odds ratios, Risk Ratios, and Risk Differences](https://www.fharrell.com/post/varyor/) argues in favour of the use of odds ratios for modelling, and points out the extreme difficulty of identifying heterogeneous treatment effects even in very large studies; and\n- [Unadjusted Odds Ratios are Conditional](https://www.fharrell.com/post/marg/) demonstrates noncollapsibility and argues that conditional odds ratios are more useful than marginal odds ratios.\n\nOne issue which I remain unclear about is whether randomised trials powered to detect main treatment effects are likely to reasonably estimate patient-specific baseline risk --- a simpler task than patient-specific treatment effects, but still outside of the usual design remit for an efficacy trial. Common analytical approaches for clinical trials have good properties for estimating average treatment effects when the covariates are regarded as nuisance parameters [@white2021covariateadjustmentrandomised], but are not guaranteed to perform so well if the effects of the covariates are themselves of interest.\n\nFinally, there is the meta-analytic perspective to consider. An effect size which is less heterogeneous between studies is once again desirable. If arguments about the transportability of odds ratios by the Harrell, Senn, Doi, and others are to be believed, we should report odds ratios, as those are likely to be the most useful for meta-analysts. There is some merit in reporting all commonly-used effect size measures: risk difference, relative risk, and odds ratio. This provides the most flexibility for future meta-analysts.\n\nIf all of that was a bit much to take in, maybe this will help:\n\n![True facts on both sides.](american-chopper-argument.jpeg){fig-alt=\"American Chopper argument meme: risk differences aren't transportable / nobody understands odds ratios / clinical trials aren't random samples from the population / marginal odds ratios aren't the average of conditional odds ratios / conditional odds ratios still tell us if an intervention works\"}\n\nIn the rest of this post I'll demonstrate how odds ratios are noncollapsible and show how to calculate risk differences and relative risks from logistic regression models using R and the `marginaleffects` package.\n\n## An example\n\nThis is the story of some hypothetical researchers who did a randomised controlled trial (RCT) where 560 patients were randomly assigned to either a treatment or control condition. The primary outcome of the trial was a binary measure, indicating whether a patient's condition had worsened after 6 weeks. The scenario is based on [one from Frank Harrell's blog](https://www.fharrell.com/post/marg/), with the details changed and embellished.\n\nThe hidden R code block below loads some R packages and sets up some simulated data for this trial.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(tidyverse)\nlibrary(gt)\nlibrary(gtsummary)\nlibrary(broom)\nlibrary(cowplot)\nlibrary(marginaleffects)\n\ntheme_set(\n  theme_cowplot(font_size = 11, rel_large = 1, rel_small = 1, rel_tiny = 1)\n)\n\nrct_data <- tribble(\n  ~treatment, ~risk, ~outcome_prob,\n  \"Control\", \"Low risk\", 1/7,\n  \"Control\", \"High risk\", 3/5,\n  \"Treatment\", \"Low risk\", 1/10,\n  \"Treatment\", \"High risk\", 1/2\n) %>%\n  mutate(across(c(treatment, risk), fct_inorder)) %>%\n  rowwise(everything()) %>%\n  reframe(\n    outcome = rep(c(1, 0), times = round(140*c(outcome_prob, 1 - outcome_prob)))\n  )\n```\n:::\n\n\nLooking at a 2-way table of our hypothetical trial, we can see that the worse outcome (\"1\") is more common in the control group (37%) than the treatment group (30%). This is an absolute risk reduction of 7%, a promising sign that our treatment may be beneficial.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_cross(rct_data, outcome, treatment, percent = \"column\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"fzoyqxtuja\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fzoyqxtuja table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fzoyqxtuja thead, #fzoyqxtuja tbody, #fzoyqxtuja tfoot, #fzoyqxtuja tr, #fzoyqxtuja td, #fzoyqxtuja th {\n  border-style: none;\n}\n\n#fzoyqxtuja p {\n  margin: 0;\n  padding: 0;\n}\n\n#fzoyqxtuja .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fzoyqxtuja .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fzoyqxtuja .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fzoyqxtuja .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fzoyqxtuja .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fzoyqxtuja .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fzoyqxtuja .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fzoyqxtuja .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fzoyqxtuja .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fzoyqxtuja .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fzoyqxtuja .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fzoyqxtuja .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fzoyqxtuja .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fzoyqxtuja .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fzoyqxtuja .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzoyqxtuja .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fzoyqxtuja .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fzoyqxtuja .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fzoyqxtuja .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzoyqxtuja .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fzoyqxtuja .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzoyqxtuja .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fzoyqxtuja .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzoyqxtuja .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fzoyqxtuja .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzoyqxtuja .gt_left {\n  text-align: left;\n}\n\n#fzoyqxtuja .gt_center {\n  text-align: center;\n}\n\n#fzoyqxtuja .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fzoyqxtuja .gt_font_normal {\n  font-weight: normal;\n}\n\n#fzoyqxtuja .gt_font_bold {\n  font-weight: bold;\n}\n\n#fzoyqxtuja .gt_font_italic {\n  font-style: italic;\n}\n\n#fzoyqxtuja .gt_super {\n  font-size: 65%;\n}\n\n#fzoyqxtuja .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fzoyqxtuja .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fzoyqxtuja .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fzoyqxtuja .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fzoyqxtuja .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fzoyqxtuja .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fzoyqxtuja .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"treatment\">\n        <span class=\"gt_column_spanner\">treatment</span>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Treatment\">Treatment</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">outcome</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">176 (63%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">196 (70%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">372 (66%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">104 (37%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">84 (30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">188 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">280 (100%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">280 (100%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">560 (100%)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nJust looking at a table won't convince anybody, though. At this point, our hypothetical trialists asked a statistician to help out[^lastminute]. Taking the role of the hypothetical statistician, we'll need to estimate the treatment effect in some way that also quantifies our uncertainty. Let's fit a binary logistic regression model to this data to examine the effect our treatment had on the outcome.\n\n[^lastminute]: Statisticians love being asked to help at the last minute.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlrm_unadj <- glm(\n  outcome ~ treatment,\n  family = binomial,\n  data = rct_data\n)\n```\n:::\n\n\nThe table below shows the results of this logistic regression: an odds ratio of 0.73 (95% CI: 0.51 to 1.03). The odds ratio being less than 1 indicates that the treatment was beneficial (since the outcome occurring was bad, in this case) but the p-value of 0.074 indicates this effect is not statistically significant. The trialists were sad, their dreams of publishing in the British Medical Journal scuppered.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(lrm_unadj, exponentiate = TRUE)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ispuymefhu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ispuymefhu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ispuymefhu thead, #ispuymefhu tbody, #ispuymefhu tfoot, #ispuymefhu tr, #ispuymefhu td, #ispuymefhu th {\n  border-style: none;\n}\n\n#ispuymefhu p {\n  margin: 0;\n  padding: 0;\n}\n\n#ispuymefhu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ispuymefhu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ispuymefhu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ispuymefhu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ispuymefhu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ispuymefhu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ispuymefhu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ispuymefhu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ispuymefhu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ispuymefhu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ispuymefhu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ispuymefhu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ispuymefhu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ispuymefhu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ispuymefhu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ispuymefhu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ispuymefhu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ispuymefhu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ispuymefhu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ispuymefhu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ispuymefhu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ispuymefhu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ispuymefhu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ispuymefhu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ispuymefhu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ispuymefhu .gt_left {\n  text-align: left;\n}\n\n#ispuymefhu .gt_center {\n  text-align: center;\n}\n\n#ispuymefhu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ispuymefhu .gt_font_normal {\n  font-weight: normal;\n}\n\n#ispuymefhu .gt_font_bold {\n  font-weight: bold;\n}\n\n#ispuymefhu .gt_font_italic {\n  font-style: italic;\n}\n\n#ispuymefhu .gt_super {\n  font-size: 65%;\n}\n\n#ispuymefhu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ispuymefhu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ispuymefhu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ispuymefhu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ispuymefhu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ispuymefhu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ispuymefhu .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;OR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>OR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">treatment</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Control</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Treatment</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.73</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.51, 1.03</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.074</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Adding a covariate\n\nJust as the statistician was finishing writing up the results, the trialists mentioned that the patients they recruited came from two different groups, one of which was known to have much worse outcomes than the other. \n\n\"Does that matter?\" they asked. \n\n\"Well, using this information could improve your statistical power\" said the statistician.\n\nThe statistician made another 2-way table, stratified by the risk group. Through some fluke, exactly half of the trial sample was low risk and the other half high risk, perfectly balanced across treatment arms. It turned out that while only 14% of the low risk patients in the control arm experienced the adverse outcome, 60% of the high risk patients in the control arm experienced the outcome.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_strata(rct_data, risk, tbl_cross, outcome, treatment, percent = \"column\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"uubpajidnk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uubpajidnk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uubpajidnk thead, #uubpajidnk tbody, #uubpajidnk tfoot, #uubpajidnk tr, #uubpajidnk td, #uubpajidnk th {\n  border-style: none;\n}\n\n#uubpajidnk p {\n  margin: 0;\n  padding: 0;\n}\n\n#uubpajidnk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uubpajidnk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uubpajidnk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uubpajidnk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uubpajidnk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uubpajidnk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uubpajidnk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uubpajidnk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uubpajidnk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uubpajidnk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uubpajidnk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uubpajidnk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uubpajidnk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uubpajidnk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uubpajidnk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uubpajidnk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uubpajidnk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uubpajidnk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uubpajidnk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uubpajidnk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uubpajidnk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uubpajidnk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uubpajidnk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uubpajidnk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uubpajidnk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uubpajidnk .gt_left {\n  text-align: left;\n}\n\n#uubpajidnk .gt_center {\n  text-align: center;\n}\n\n#uubpajidnk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uubpajidnk .gt_font_normal {\n  font-weight: normal;\n}\n\n#uubpajidnk .gt_font_bold {\n  font-weight: bold;\n}\n\n#uubpajidnk .gt_font_italic {\n  font-style: italic;\n}\n\n#uubpajidnk .gt_super {\n  font-size: 65%;\n}\n\n#uubpajidnk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uubpajidnk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uubpajidnk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uubpajidnk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uubpajidnk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uubpajidnk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uubpajidnk .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"&lt;strong&gt;Low risk&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Low risk</strong></span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"&lt;strong&gt;High risk&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>High risk</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Treatment\">Treatment</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Treatment\">Treatment</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">outcome</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">120 (86%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">126 (90%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">246 (88%)</td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">56 (40%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">70 (50%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">126 (45%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">20 (14%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">14 (10%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">34 (12%)</td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">84 (60%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">70 (50%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">154 (55%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">140 (100%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">140 (100%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">280 (100%)</td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">140 (100%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">140 (100%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">280 (100%)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nThe statistician decided to fit another logistic regression model, this time including risk as an additional variable in the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlrm_adj <- glm(\n  outcome ~ treatment + risk,\n  family = binomial,\n  data = rct_data\n)\n```\n:::\n\n\nLooking at the coefficients in this model, we can see that the estimated effect of treatment has increased: the odds ratio is further away from 1, now being 0.67 (95% CI: 0.45 to 0.99) instead of 0.73 (95% CI: 0.51 to 1.03). The p-value has decreased from 0.074 to 0.045, meaning that the treatment effect is now statistically significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(lrm_adj, exponentiate = TRUE)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"stzxfemmsl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#stzxfemmsl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#stzxfemmsl thead, #stzxfemmsl tbody, #stzxfemmsl tfoot, #stzxfemmsl tr, #stzxfemmsl td, #stzxfemmsl th {\n  border-style: none;\n}\n\n#stzxfemmsl p {\n  margin: 0;\n  padding: 0;\n}\n\n#stzxfemmsl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#stzxfemmsl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#stzxfemmsl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#stzxfemmsl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#stzxfemmsl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#stzxfemmsl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#stzxfemmsl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#stzxfemmsl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#stzxfemmsl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#stzxfemmsl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#stzxfemmsl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#stzxfemmsl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#stzxfemmsl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#stzxfemmsl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#stzxfemmsl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#stzxfemmsl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#stzxfemmsl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#stzxfemmsl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#stzxfemmsl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#stzxfemmsl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#stzxfemmsl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#stzxfemmsl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#stzxfemmsl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#stzxfemmsl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#stzxfemmsl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#stzxfemmsl .gt_left {\n  text-align: left;\n}\n\n#stzxfemmsl .gt_center {\n  text-align: center;\n}\n\n#stzxfemmsl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#stzxfemmsl .gt_font_normal {\n  font-weight: normal;\n}\n\n#stzxfemmsl .gt_font_bold {\n  font-weight: bold;\n}\n\n#stzxfemmsl .gt_font_italic {\n  font-style: italic;\n}\n\n#stzxfemmsl .gt_super {\n  font-size: 65%;\n}\n\n#stzxfemmsl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#stzxfemmsl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#stzxfemmsl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#stzxfemmsl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#stzxfemmsl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#stzxfemmsl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#stzxfemmsl .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;OR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>OR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">treatment</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Control</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Treatment</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.67</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.45, 0.99</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.045</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">risk</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Low risk</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    High risk</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">9.00</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">5.91, 14.0</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe trialists went home happy, dreaming once again of publishing in a high impact factor journal, but the statistician was left with a nagging feeling that something was not quite right. The covariate was balanced between treatment groups, with equal numbers of low risk and high risk assigned to each treatment. Undergraduate linear models courses taught that adding a covariate to the model in this scenario shouldn't change the coefficient for treatment, only the standard error. Why, then, did the estimates change like that? Is logistic regression different from linear regression in this regard?\n\n## Hand calculations: back to the 2-way table\n\nLet's take another look at the 2-way table and do some hand calculations.\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"nevgpityxm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nevgpityxm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nevgpityxm thead, #nevgpityxm tbody, #nevgpityxm tfoot, #nevgpityxm tr, #nevgpityxm td, #nevgpityxm th {\n  border-style: none;\n}\n\n#nevgpityxm p {\n  margin: 0;\n  padding: 0;\n}\n\n#nevgpityxm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nevgpityxm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nevgpityxm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nevgpityxm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nevgpityxm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nevgpityxm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nevgpityxm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nevgpityxm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nevgpityxm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nevgpityxm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nevgpityxm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nevgpityxm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nevgpityxm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nevgpityxm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nevgpityxm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nevgpityxm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nevgpityxm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nevgpityxm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nevgpityxm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nevgpityxm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nevgpityxm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nevgpityxm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nevgpityxm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nevgpityxm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nevgpityxm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nevgpityxm .gt_left {\n  text-align: left;\n}\n\n#nevgpityxm .gt_center {\n  text-align: center;\n}\n\n#nevgpityxm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nevgpityxm .gt_font_normal {\n  font-weight: normal;\n}\n\n#nevgpityxm .gt_font_bold {\n  font-weight: bold;\n}\n\n#nevgpityxm .gt_font_italic {\n  font-style: italic;\n}\n\n#nevgpityxm .gt_super {\n  font-size: 65%;\n}\n\n#nevgpityxm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nevgpityxm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nevgpityxm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nevgpityxm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nevgpityxm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nevgpityxm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nevgpityxm .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"treatment\">\n        <span class=\"gt_column_spanner\">treatment</span>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Treatment\">Treatment</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">outcome</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">176 (63%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">196 (70%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">372 (66%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">104 (37%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">84 (30%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">188 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">280 (100%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">280 (100%)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">560 (100%)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nThe marginal risk difference is the difference between treatment and control groups in the proportion of patients experiencing the outcome event. From the table above, ignoring the covariate, we can calculate a risk reduction of 0.071:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n104/280 - 84/280\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.07142857\n```\n:::\n:::\n\n\nThe marginal odds ratio is the ratio of the oddses for treatment and the control group, where the odds is itself the number who experience the outcome event divided by the number who do not[^orargh]. We can calculate the marginal odds ratio here as 0.73, the same as the unadjusted logistic regression:\n\n[^orargh]: The odds ratio is a ratio of ratios, no wonder nobody understands them.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n(84/196) / (104/176)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7252747\n```\n:::\n:::\n\n\nNow let's look at the table stratified by risk, and see how that affects our calculations.\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"jgbgxpjqmn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jgbgxpjqmn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jgbgxpjqmn thead, #jgbgxpjqmn tbody, #jgbgxpjqmn tfoot, #jgbgxpjqmn tr, #jgbgxpjqmn td, #jgbgxpjqmn th {\n  border-style: none;\n}\n\n#jgbgxpjqmn p {\n  margin: 0;\n  padding: 0;\n}\n\n#jgbgxpjqmn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jgbgxpjqmn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jgbgxpjqmn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jgbgxpjqmn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jgbgxpjqmn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jgbgxpjqmn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jgbgxpjqmn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jgbgxpjqmn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jgbgxpjqmn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jgbgxpjqmn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jgbgxpjqmn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jgbgxpjqmn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jgbgxpjqmn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jgbgxpjqmn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jgbgxpjqmn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgbgxpjqmn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jgbgxpjqmn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jgbgxpjqmn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jgbgxpjqmn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgbgxpjqmn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jgbgxpjqmn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgbgxpjqmn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jgbgxpjqmn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgbgxpjqmn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jgbgxpjqmn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgbgxpjqmn .gt_left {\n  text-align: left;\n}\n\n#jgbgxpjqmn .gt_center {\n  text-align: center;\n}\n\n#jgbgxpjqmn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jgbgxpjqmn .gt_font_normal {\n  font-weight: normal;\n}\n\n#jgbgxpjqmn .gt_font_bold {\n  font-weight: bold;\n}\n\n#jgbgxpjqmn .gt_font_italic {\n  font-style: italic;\n}\n\n#jgbgxpjqmn .gt_super {\n  font-size: 65%;\n}\n\n#jgbgxpjqmn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jgbgxpjqmn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jgbgxpjqmn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jgbgxpjqmn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jgbgxpjqmn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jgbgxpjqmn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jgbgxpjqmn .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"&lt;strong&gt;Low risk&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Low risk</strong></span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"&lt;strong&gt;High risk&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>High risk</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Treatment\">Treatment</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Control\">Control</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Treatment\">Treatment</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">outcome</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    0</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">120 (86%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">126 (90%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">246 (88%)</td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">56 (40%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">70 (50%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">126 (45%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">20 (14%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">14 (10%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">34 (12%)</td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">84 (60%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">70 (50%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">154 (55%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"stat_1_1\" class=\"gt_row gt_center\">140 (100%)</td>\n<td headers=\"stat_2_1\" class=\"gt_row gt_center\">140 (100%)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">280 (100%)</td>\n<td headers=\"stat_1_2\" class=\"gt_row gt_center\">140 (100%)</td>\n<td headers=\"stat_2_2\" class=\"gt_row gt_center\">140 (100%)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">280 (100%)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nUsing the same formula as before, we can calculate a risk difference of 0.043 in the low risk group, 0.100 in the high risk group, and the equally-weighted average of those two (because the two risk groups are equally common in this example) is 0.071, same as the marginal risk difference calculated above.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# conditional risk difference in the low risk group\n20/140 - 14/140\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04285714\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# conditional risk difference in the high risk group\n84/140 - 70/140\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# average of conditional risk differences is the marginal risk difference\n0.5*((20/140 - 14/140) + (84/140 - 70/140))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.07142857\n```\n:::\n:::\n\n\nUsing the formula for odds ratios, we can calculate an odds ratio of 0.67 in the low risk group and 0.67 in the high risk group. The conditional odds ratios in both groups are equal, and equal to the conditional odds ratio from the adjusted logistic regression, but are different from the marginal odds ratio. This is noncollapsibility in action.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# conditional odds ratio in the low risk group\n(14/126) / (20/120)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6666667\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# conditional odds ratio in the high risk group\n(70/70) / (84/56)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6666667\n```\n:::\n:::\n\n\nIn this example, we observed a treatment-by-risk-group interaction on the risk difference scale (absolute risk reduction of 0.041 in the low-risk group, absolute risk reduction of 0.100 in the high-risk group) but not on the odds ratio scale (conditional odds ratio of 0.67 in both groups). There is no mathematical requirement for the odds ratio scale to have a smaller interaction than other scales, but it is mathematically impossible for there to be no interaction on *any* scale unless the effect size is zero. This issue is discussed in detail from the perspective of psychological research in @rohrer2021preciseanswersvague.\n\n## Calculating risk difference and relative risks using the marginaleffects package\n\n\n\n\n\nThe trialists returned to the statistician, requesting adjusted and unadjusted risk differences and relative risks to report in their paper. Fortunately, the statistician was familiar with the `marginaleffects` package, which makes it fairly easy to calculate risk differences from logistic regression models[^stderr].\n\n[^stderr]: One thing to be aware of is that the standard errors are derived using the delta method, which is a large-sample approximation. There is experimental support for bootstrapping and simulation-based inference in the `marginaleffects` package to get more accurate estimates in small samples, but this blog post isn't going there.\n\n### Risk differences\n\nThe `avg_comparisons()` function calculates differences in one variable, averaged across the observed distribution of the other variables. By default it does this calculation on the response scale, i.e. predicted probability, which is what we want for a risk difference. For the unadjusted model, we get an average risk reduction of 7.1% (95% CI: -0.1% to 14.9%).\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(lrm_unadj, variables = \"treatment\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n      Term Contrast Estimate Std. Error     z Pr(>|z|)   S  2.5 %  97.5 %\n treatment    T - C  -0.0714     0.0398 -1.79   0.0727 3.8 -0.149 0.00657\n\nColumns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high \n```\n:::\n:::\n\n\nFor the adjusted model, we get an average risk reduction of 7.1% (95% CI: 0.0% to 14.1%).\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(lrm_adj, variables = \"treatment\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n      Term Contrast Estimate Std. Error     z Pr(>|z|)   S  2.5 %   97.5 %\n treatment    T - C  -0.0714     0.0354 -2.02   0.0437 4.5 -0.141 -0.00201\n\nColumns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high \n```\n:::\n:::\n\n\nUnlike the odds ratio, the point estimate of the risk difference didn't change when we added the covariate, but its estimate got more precise: the confidence interval shrank.\n\n### Relative risks\n\nTo get relative risks using `avg_comparisons()`, we need to ask for the average of the log of the ratio between treatment conditions (`lnratioavg` in the code below), and then exponentiate that.\n\nFor the unadjusted model, the relative risk is 0.81 (95% CI: 0.64 to 1.02).\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(lrm_unadj, variables = \"treatment\",\n                comparison = \"lnratioavg\", transform = \"exp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n      Term              Contrast Estimate Pr(>|z|)   S 2.5 % 97.5 %\n treatment ln(mean(T) / mean(C))    0.808   0.0749 3.7 0.639   1.02\n\nColumns: term, contrast, estimate, p.value, s.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo \n```\n:::\n:::\n\n\nFor the adjusted model, the relative risk is 0.81 (95% CI: 0.65 to 1.00).\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(lrm_adj, variables = \"treatment\",\n                comparison = \"lnratioavg\", transform = \"exp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n      Term              Contrast Estimate Pr(>|z|)   S 2.5 % 97.5 %\n treatment ln(mean(T) / mean(C))    0.808   0.0458 4.4 0.655  0.996\n\nColumns: term, contrast, estimate, p.value, s.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo \n```\n:::\n:::\n\n\nCompared to the unadjusted model, the point estimate hasn't changed but the confidence interval shrank. Like risk differences, and unlike odds ratios, relative risks are collapsible.\n\n## In pictures\n\nOne last way of showing the same thing: below is a plot of unadjusted and adjusted odds ratios, risk differences, and relative risks. You can see that for the odds ratio, the adjustment has moved the point estimate but not made the confidence interval narrower, whereas for the other measures, the point estimate has not changed but the confidence intervals are narrower for the adjusted estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# odds ratio estimates\nor_estimates <- bind_rows(\n  \"Unadjusted\" = \n    tidy(lrm_unadj, conf.int = TRUE, exponentiate = TRUE) %>%\n    filter(term == \"treatmentT\"),\n  \"Adjusted\" = \n    tidy(lrm_adj, conf.int = TRUE, exponentiate = TRUE) %>%\n    filter(term == \"treatmentT\"),\n  .id = \"model\"\n) %>%\n  select(model, estimate, conf.low, conf.high)\n\n# risk difference estimates\nrd_estimates <- bind_rows(\n  \"Unadjusted\" =\n    avg_comparisons(lrm_unadj, variables = \"treatment\"),\n  \"Adjusted\" =\n    avg_comparisons(lrm_adj, variables = \"treatment\"),\n  .id = \"model\"\n) %>%\n  select(model, estimate, conf.low, conf.high)\n\n# relative risk estimates\nrr_estimates <- bind_rows(\n  \"Unadjusted\" =\n    avg_comparisons(lrm_unadj, variables = \"treatment\",\n                    comparison = \"lnratioavg\", transform = \"exp\"),\n  \"Adjusted\" =\n    avg_comparisons(lrm_adj, variables = \"treatment\",\n                    comparison = \"lnratioavg\", transform = \"exp\"),\n  .id = \"model\"\n) %>%\n  select(model, estimate, conf.low, conf.high)\n\n# combine all estimands into a single data frame\nall_estimates <- bind_rows(\n  \"Odds ratio\" = or_estimates,\n  \"Risk difference\" = rd_estimates,\n  \"Relative risk\" = rr_estimates,\n  .id = \"estimand\"\n)\n\n# plot!\nall_estimates %>%\n  mutate(model = fct_inorder(model), estimand = fct_inorder(estimand)) %>%\n  ggplot(aes(x = estimate, xmin = conf.low, xmax = conf.high,\n             y = model)) +\n  geom_pointrange() +\n  scale_y_discrete(limits = rev) +\n  facet_wrap(vars(estimand), nrow = 3, scales = \"free\") +\n  panel_border() +\n  labs(y = NULL, x = \"Estimate (95% CI)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/coef-plot-1.png){width=780}\n:::\n:::\n\n\n## Acknowledgements\n\nThanks to those who provided feedback on earlier versions of this post, some which resulted in substantial revisions and improvements:\n\n- Isabella Ghement\n- Lachlan Cribb\n\nFeedback welcome, especially any corrections in cases where I may have misunderstood or misattributed arguments, or made clear factual errors.\n\n## References\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}